export const GET_LIVE_STREAM_DATA_REQ= 'GET_LIVE_STREAM_DATA_REQ';
export const LIVE_STREAM_DATA_REQ_SUCESS= 'LIVE_STREAM_DATA_REQ_SUCESS';
export const LIVE_STREAM_DATA_REQ_FAIL= 'LIVE_STREAM_DATA_REQ_FAIL';

